abstract: Jifty plugin to a add dynamic ldap authorization
author: Yves Agostini, <yvesago@cpan.org>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: Jifty-Plugin-AuthzLDAP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::MemoryCache: 0
  Jifty: 0.70416
  Net::LDAP: 0
tests: t/*.t
version: 0.02
