---
abstract: 'Jifty plugin to a add dynamic ldap authorization'
author:
  - 'Yves Agostini, <yvesago@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-AuthzLDAP
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Cache::MemoryCache: 0
  Jifty: 0.70416
  Net::LDAP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.9
